/* End-to-end browser verification. Run with Node and Playwright available in NODE_PATH.
   Starts no server; serve html/ at ARCADE_BASE (default http://127.0.0.1:8000).
   Production code contains no testing hooks. Clock control speeds up real game sessions. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=process.env.ARCADE_BASE||'http://127.0.0.1:8000';
const out=process.env.ARCADE_TEST_OUTPUT||'/tmp/ms-arcade-tests';fs.mkdirSync(out,{recursive:true});
const ids=['memory-match','treat-catch','wheres-molly','trivia','pawprint-maze','molly-dash','fetch','who-is-it','photo-puzzle','treat-stacker','sniff-hunt','mollys-house','reaction-paws','doggy-drawing','molly-vs-shaina','ultimate-dog-challenge'];
const records=[];
let browser,page,context,errors=[];
async function test(name,fn){try{await fn();records.push({name,pass:true});console.log('PASS '+name);}catch(error){records.push({name,pass:false,error:error.stack});console.log('FAIL '+name+': '+error.message);if(page&&!page.isClosed())await page.screenshot({path:path.join(out,name.replace(/[^a-z0-9]+/gi,'-')+'.png'),fullPage:true,animations:'disabled'}).catch(()=>{});}}
async function setup(mobile=false){
 context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile,reducedMotion:'reduce'});
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!==base)return route.fulfill({status:200,body:'',contentType:url.pathname.endsWith('.js')?'application/javascript':'text/css'});if(url.pathname==='/api/posts')return route.fulfill({path:path.resolve('html/blog/posts.json'),contentType:'application/json'});return route.continue();});
 page=await context.newPage();errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))errors.push(`${r.status()} ${r.url()}`);});
 await page.clock.install({time:new Date('2026-09-15T10:00:00Z')});await page.goto(base+'/games/',{waitUntil:'networkidle'});await page.locator('.arcade-card').first().waitFor();await page.clock.pauseAt(new Date('2026-09-15T10:10:00Z'));await page.clock.runFor(50);
}
const advance=ms=>page.clock.runFor(ms);
async function seed(n=816){await page.evaluate(n=>{let state=n;Math.random=()=>{state=(Math.imul(1664525,state)+1013904223)>>>0;return state/4294967296;};},n);}
async function start(id){await page.evaluate(id=>{location.hash=id;},id);await page.locator('#start-game').waitFor();await seed();await page.locator('#start-game').click();await advance(32);await page.evaluate(async()=>Promise.all([...document.querySelectorAll('#game-stage img')].map(i=>i.decode().catch(()=>{}))));}
async function finished(id,won){await page.locator('#play-again').waitFor({timeout:3000});const r=await page.evaluate(id=>JSON.parse(localStorage.getItem('msArcadeV1')).results[id],id);assert.ok(r.plays>=1);assert.ok(Number.isFinite(r.best));if(won)assert.ok(r.wins>=1,`${id} should have a win`);return r;}
async function click(selector){const locator=page.locator(selector);if(await context._options?.hasTouch)await locator.tap();else await locator.click();}
async function screenshot(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true,animations:'disabled'});}
async function smoke(mobile){await setup(mobile);assert.equal(await page.locator('.arcade-card').count(),16);await screenshot(mobile?'hub-mobile':'hub-desktop');
 for(const id of ids)await test(`${mobile?'mobile':'desktop'} ${id}: instructions, play, pause, restart`,async()=>{await start(id);assert.ok((await page.locator('#game-stage').innerText()).length||await page.locator('#game-stage canvas').count());assert.equal(await page.locator('#game-stage').evaluate(e=>e.scrollWidth>e.clientWidth+1),false,'stage overflows horizontally');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'page overflows horizontally');const before=await page.locator('#game-hud').innerText();await page.locator('#pause-game').click();await advance(5000);assert.equal(await page.locator('#game-hud').innerText(),before);assert.equal(await page.locator('#pause-cover').isVisible(),true);await page.locator('#resume-game').click();await page.locator('#restart-game').click();await advance(32);assert.equal(await page.locator('#play-again').count(),0);assert.equal(await page.locator('#pause-cover').isVisible(),false);if(mobile)await screenshot('mobile-'+id);});
 await test(`${mobile?'mobile':'desktop'} assets and console`,async()=>{assert.deepEqual(errors,[]);const failures=await page.evaluate(async()=>{const {catalog,photos,assets}=await import('/js/arcade/data.js');const urls=[...new Set([...catalog.map(g=>g.image),...photos.map(p=>p.src),...Object.values(assets)])];return(await Promise.all(urls.map(src=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(null);img.onerror=()=>resolve(src);img.src=src;})))).filter(Boolean);});assert.deepEqual(failures,[]);});await context.close();}
async function mazeWin(){await start('pawprint-maze');let position=[1,1];for(let goal=0;goal<4;goal++){
 const state=await page.locator('.maze-board').evaluate(e=>[...e.children].map(c=>({wall:c.classList.contains('wall'),text:c.textContent})));let target=goal<3?state.findIndex(c=>c.text.includes('🦴')):108;assert.ok(target>=0);const queue=[[position[0]+position[1]*11,[]]],seen=new Set();let route;while(queue.length){const [i,steps]=queue.shift();if(i===target){route=steps;break;}if(seen.has(i))continue;seen.add(i);for(const[d,key]of[[-11,'ArrowUp'],[11,'ArrowDown'],[-1,'ArrowLeft'],[1,'ArrowRight']])if(state[i+d]&&!state[i+d].wall&&!seen.has(i+d))queue.push([i+d,[...steps,key]]);}assert.ok(route);for(const key of route){await page.keyboard.press(key);if(key==='ArrowUp')position[1]--;if(key==='ArrowDown')position[1]++;if(key==='ArrowLeft')position[0]--;if(key==='ArrowRight')position[0]++;} }
 await finished('pawprint-maze',true);
}
async function houseWin(){await start('mollys-house');for(const id of ['blanket','ball','bone','bowl','portrait','paw']){await page.locator(`[data-item=${id}]`).click();await page.locator(`[data-place=${id}]`).click();}await finished('mollys-house',true);}
async function drawingWin(){await start('doggy-drawing');const canvas=page.locator('#game-stage canvas');await canvas.focus();for(let i=0;i<3;i++){if(i===1){await page.locator('[data-colour]').nth(1).click();await canvas.focus();}await page.keyboard.press('Space');for(let j=0;j<8;j++)await page.keyboard.press(i%2?'ArrowDown':'ArrowRight');await page.keyboard.press('Space');}await page.locator('[data-stamp=molly]').click();await page.locator('[data-action=save]').click();assert.ok(await page.evaluate(()=>localStorage.getItem('msArcadeDrawingV1')?.includes('data:image/png')));await page.locator('[data-action=clear]').click();await page.locator('[data-action=load]').click();await page.waitForFunction(()=>!document.querySelector('[data-action=finish]').disabled);await screenshot('drawing-desktop');await page.locator('[data-action=finish]').click();await finished('doggy-drawing',true);const download=page.waitForEvent('download');await page.locator('a[download]').click();assert.equal((await download).suggestedFilename(),'molly-and-shaina-masterpiece.png');}
async function versusWin(){await start('molly-vs-shaina');let last=-1;for(let time=0;time<42000;time+=32){await advance(32);if(await page.locator('#play-again').count())break;const marker=await page.locator('.rhythm-cursor').evaluate(e=>parseFloat(e.style.left));if(marker>=41&&marker<=58&&time-last>300){await page.keyboard.press('Space');last=time;}}await finished('molly-vs-shaina',true);}
async function sniffWin(){await start('sniff-hunt');let candidates=[];for(let a=0;a<23;a++)for(let b=a+1;b<24;b++)for(let c=b+1;c<25;c++)candidates.push([a,b,c]);const dug=new Set();for(let turn=0;turn<12;turn++){const counts=Array(25).fill(0);candidates.forEach(s=>s.forEach(i=>{if(!dug.has(i))counts[i]++;}));const tile=turn===0?12:counts.indexOf(Math.max(...counts));await page.locator('.sniff-tile').nth(tile).click();if(await page.locator('#play-again').count())break;const label=await page.locator('.sniff-tile').nth(tile).getAttribute('aria-label');dug.add(tile);if(label==='Treat found')candidates=candidates.filter(s=>s.includes(tile)).map(s=>s.filter(i=>i!==tile));else{const distance=Number(label.match(/(\d+) steps/)[1]);candidates=candidates.filter(s=>!s.includes(tile)&&Math.min(...s.map(i=>Math.abs(i%5-tile%5)+Math.abs(Math.floor(i/5)-Math.floor(tile/5))))===distance);}assert.ok(candidates.length);}await finished('sniff-hunt',true);}
async function finaleWin(){await start('ultimate-dog-challenge');for(let r=1;r<=12;r++){
 const mode=(r-1)%4;if(mode===0){const src=await page.locator('.finale-photo').getAttribute('src');await page.keyboard.press(src.includes('/molly/')?'1':'2');}
 if(mode===1){const options=await page.locator('.finale-targets button').allTextContents();await page.keyboard.press(String(options.findIndex(t=>t.includes('🦴'))+1));}
 if(mode===2){const sequence=[];let previous=-1;for(let t=0;t<5000;t+=100){await advance(100);const lit=await page.locator('.finale-targets button').evaluateAll(bs=>bs.findIndex(b=>b.classList.contains('lit')));if(lit>=0&&lit!==previous)sequence.push(lit);previous=lit;if((await page.locator('#finale-prompt').innerText()).startsWith('Repeat'))break;}assert.equal(sequence.length,2+Math.floor(r/4));for(const i of sequence)await page.keyboard.press(String(i+1));}
 if(mode===3){const prompt=await page.locator('#finale-prompt').innerText();const correct=await page.evaluate(async prompt=>{const{trivia}=await import('/js/arcade/data.js');const q=trivia.find(q=>q.question===prompt);return q.options[q.answer];},prompt);const options=await page.locator('.finale-targets button span').allTextContents();await page.keyboard.press(String(options.indexOf(correct)+1));}
 if(r<12)await page.locator('#finale-next').click();else await advance(1000);
 }await finished('ultimate-dog-challenge',true);}
async function progression(){const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('msArcadeV1')));assert.ok(state.coins>0);assert.ok(state.achievements['first-paw']);await page.locator('#mute-toggle').click();const muted=await page.evaluate(()=>JSON.parse(localStorage.getItem('msArcadeV1')).muted);await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('msArcadeV1')).coins),state.coins);assert.equal(await page.locator('#mute-toggle').getAttribute('aria-pressed'),String(muted));assert.equal(await page.evaluate(()=>localStorage.getItem('arcade-regression-sentinel')),'keep-me');}
async function adventures(){await setup();await page.evaluate(()=>localStorage.setItem('arcade-regression-sentinel','keep-me'));for(const [name,fn]of[['Pawprint Maze keyboard full win',mazeWin],["Molly’s House all placements",houseWin],['Doggy Drawing keyboard save load download',drawingWin],['Molly vs Shaina timing race win',versusWin],['Sniff Hunt clue-driven full win',sniffWin],['Ultimate Dog Challenge twelve escalating rounds',finaleWin],['Progress persists after reload and mute',progression]])await test(name,fn);
 for(const [id,ms]of[['pawprint-maze',91000],['mollys-house',61000],['molly-vs-shaina',46000]])await test(id+' timed loss and no duplicate payout',async()=>{await start(id);await advance(ms);await finished(id,false);const before=await page.evaluate(()=>localStorage.getItem('msArcadeV1'));await advance(10000);assert.equal(await page.evaluate(()=>localStorage.getItem('msArcadeV1')),before);});
 await test('Ultimate finale three missed rounds loses',async()=>{await start('ultimate-dog-challenge');for(let i=0;i<3;i++){await advance(15000);if(i<2)await page.locator('#finale-next').click();}await advance(1000);await finished('ultimate-dog-challenge',false);assert.match(await page.locator('.result-screen').innerText(),/Good effort/);});await test('Adventure console clean',async()=>assert.deepEqual(errors,[]));await context.close();}
(async()=>{browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const mode=process.argv[2]||'all';if(mode==='all'||mode==='smoke'){await smoke(false);await smoke(true);}if(mode==='all'||mode==='adventures')await adventures();}finally{await browser.close();fs.writeFileSync(path.join(out,'browser-results-'+(process.argv[2]||'all')+'.json'),JSON.stringify(records,null,2));console.log(`${records.filter(r=>r.pass).length}/${records.length} passed`);process.exitCode=records.some(r=>!r.pass)?1:0;}})().catch(e=>{console.error(e);process.exitCode=1;browser?.close();});
