import {assets,photos,trivia,randomInt,shuffle} from './data.js';
import {DRAWING_KEY} from './progress.js';
const $=(ctx,s)=>ctx.root.querySelector(s);
function directions(ctx,move){const pad=document.createElement('div');pad.className='dpad';pad.innerHTML='<button class="game-button" aria-label="Move up">↑</button><button class="game-button" aria-label="Move left">←</button><button class="game-button" aria-label="Move down">↓</button><button class="game-button" aria-label="Move right">→</button>';ctx.root.append(pad);const dirs=[[0,-1],[-1,0],[0,1],[1,0]];pad.querySelectorAll('button').forEach((b,i)=>ctx.on(b,'click',()=>move(...dirs[i])));ctx.on(document,'keydown',e=>{const d={ArrowUp:[0,-1],KeyW:[0,-1],ArrowLeft:[-1,0],KeyA:[-1,0],ArrowDown:[0,1],KeyS:[0,1],ArrowRight:[1,0],KeyD:[1,0]}[e.code];if(d){e.preventDefault();move(...d);}});}
function maze(ctx){const n=11,map=Array.from({length:n},()=>Array(n).fill(1)),stack=[[1,1]];map[1][1]=0;while(stack.length){const[x,y]=stack.at(-1),options=shuffle([[2,0],[-2,0],[0,2],[0,-2]]).filter(([dx,dy])=>x+dx>0&&x+dx<n-1&&y+dy>0&&y+dy<n-1&&map[y+dy][x+dx]);if(!options.length){stack.pop();continue;}const[dx,dy]=options[0];map[y+dy/2][x+dx/2]=0;map[y+dy][x+dx]=0;stack.push([x+dx,y+dy]);}
 let x=1,y=1,moves=0,collected=0;const cells=[];for(let yy=1;yy<n-1;yy++)for(let xx=1;xx<n-1;xx++)if(!map[yy][xx]&&!(xx===1&&yy===1)&&!(xx===9&&yy===9))cells.push(`${xx},${yy}`);const treats=new Set(shuffle(cells).slice(0,3));ctx.root.innerHTML='<div class="maze-board" role="img" aria-label="Molly’s maze"></div>';const board=$ (ctx,'.maze-board');
 function render(){board.replaceChildren();for(let yy=0;yy<n;yy++)for(let xx=0;xx<n;xx++){const c=document.createElement('div');c.className='maze-cell'+(map[yy][xx]?' wall':'');if(xx===x&&yy===y)c.innerHTML=`<img src="${assets.molly}" alt="Molly">`;else if(treats.has(`${xx},${yy}`))c.textContent='🦴';else if(xx===9&&yy===9)c.textContent='🥣';board.append(c);}board.setAttribute('aria-label',`Molly at column ${x+1}, row ${y+1}. ${collected} of 3 treats found.`);ctx.hud({Treats:`${collected} / 3`,Moves:moves,Time:`${Math.max(0,90-Math.floor(ctx.elapsed))}s`});}
 function move(dx,dy){if(map[y+dy]?.[x+dx]!==0)return;x+=dx;y+=dy;moves++;if(treats.delete(`${x},${y}`)){collected++;ctx.sound('good');ctx.status(`${collected} of 3 treats found. ${collected===3?'Head for the bowl!':'Keep sniffing.'}`);}if(x===9&&y===9){if(collected===3){ctx.finish({score:Math.max(300,1300-moves*3-Math.floor(ctx.elapsed)*5),won:true,message:'Dinner is served. Every treat safely delivered!'});return;}ctx.status('The bowl is here. Collect all three treats first.');}render();}
 directions(ctx,move);ctx.status('Find three bones, then the bowl at the lower right.');render();ctx.every(()=>{render();if(ctx.elapsed>=90)ctx.finish({score:collected*150,won:false,message:'Dinner time! Try a fresh maze and follow the corridors.'});},250);
}
function sniff(ctx){const hidden=new Set(shuffle(Array.from({length:25},(_,i)=>i)).slice(0,3));let digs=0,found=0,score=0;ctx.root.innerHTML='<p class="game-note">The number is your distance from the nearest remaining treat. One step is one square across or down.</p><div class="sniff-board" role="group" aria-label="Garden digging squares"></div>';const board=$(ctx,'.sniff-board');
 function hud(){ctx.hud({Treats:`${found} / 3`,Digs:`${12-digs} left`,Score:score});}
 for(let i=0;i<25;i++){const b=document.createElement('button');b.className='sniff-tile';b.setAttribute('aria-label',`Dig row ${Math.floor(i/5)+1}, column ${i%5+1}`);b.innerHTML=`<small>${Math.floor(i/5)+1}·${i%5+1}</small><span>✿</span>`;board.append(b);ctx.on(b,'click',()=>{if(b.dataset.dug)return;b.dataset.dug='true';b.classList.add('dug');b.setAttribute('aria-disabled','true');digs++;if(hidden.delete(i)){found++;score+=250;b.querySelector('span').textContent='🦴';b.setAttribute('aria-label','Treat found');ctx.sound('good');ctx.status(`Good nose! ${found} of 3 treats found.`);}else{const distance=Math.min(...[...hidden].map(j=>Math.abs(i%5-j%5)+Math.abs(Math.floor(i/5)-Math.floor(j/5))));b.querySelector('span').textContent=distance;b.setAttribute('aria-label',`Dug: nearest treat was ${distance} steps away`);ctx.status(`${distance===1?'Very close!':distance<=3?'Getting warmer.':'A little further away.'} Nearest remaining treat: ${distance} steps.`);ctx.sound('tap');}hud();if(found===3)ctx.finish({score:score+(12-digs)*40,won:true,message:'Three treats found. Your nose deserves an award.'});else if(digs>=12)ctx.finish({score,won:false,message:`You found ${found} of 3 treats. Try using the distance clues to narrow down your next dig.`});});ctx.on(b,'keydown',e=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-5,ArrowDown:5}[e.code];if(delta){e.preventDefault();board.children[Math.max(0,Math.min(24,i+delta))].focus();}});}
 hud();ctx.status('Choose a square. Use the distance clues to plan your next dig.');
}
function house(ctx){const items=[{id:'blanket',name:'Blanket',place:'Blanket nest',src:'/images/merch/stickers/resting-dog.webp'},{id:'ball',name:'Tennis ball',place:'Toy basket',src:assets.ball},{id:'bone',name:'Treat',place:'Treat jar',src:assets.bone},{id:'bowl',name:'Food bowl',place:'Dinner mat',src:'/images/merch/stickers/dog-bowl.webp'},{id:'portrait',name:'Molly portrait',place:'Photo frame',src:'/images/merch/stickers/molly-portrait.webp'},{id:'paw',name:'Paw sticker',place:'Welcome sign',src:'/images/merch/stickers/paw-print.webp'}];let selected=null,placed=new Set(),mistakes=0;ctx.root.innerHTML='<div class="game-board"><p class="game-note">A little pretend housekeeping: blanket → nest, ball → basket, treat → jar, bowl → mat, portrait → frame, paw sticker → sign.</p><div class="house-slots"></div><div class="game-controls house-items" aria-label="Things to tidy"></div></div>';const slots=$(ctx,'.house-slots'),tray=$(ctx,'.house-items');
 function hud(){ctx.hud({Tidied:`${placed.size} / 6`,Time:`${Math.max(0,60-Math.floor(ctx.elapsed))}s`,Mistakes:mistakes});}
 function select(id){if(placed.has(id))return;selected=id;tray.querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',b.dataset.item===id);b.setAttribute('aria-pressed',String(b.dataset.item===id));});ctx.status(`${items.find(i=>i.id===id).name} selected. Choose its place.`);}
 function place(id,b){if(!selected){ctx.status('Select something from the tray first.');return;}if(placed.has(id))return;if(id!==selected){mistakes++;ctx.sound('bad');ctx.status('Molly has standards. Try the matching place.');hud();return;}const item=items.find(i=>i.id===id);placed.add(id);b.innerHTML=`<img src="${item.src}" alt="${item.name}"><span>${item.place} ✓</span>`;b.classList.add('correct');b.setAttribute('aria-disabled','true');tray.querySelector(`[data-item="${id}"]`).disabled=true;selected=null;tray.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));ctx.sound('good');ctx.status('Just where it belongs.');hud();if(placed.size===6)ctx.finish({score:Math.max(300,1000-Math.floor(ctx.elapsed)*5-mistakes*30),won:true,message:'A place for everything. Molly can finally supervise a nap.'});}
 for(const item of shuffle(items)){const b=document.createElement('button');b.className='house-slot';b.dataset.place=item.id;b.innerHTML=`<span>＋</span><span>${item.place}</span>`;slots.append(b);ctx.on(b,'click',()=>place(item.id,b));ctx.on(b,'dragover',e=>e.preventDefault());ctx.on(b,'drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(items.some(i=>i.id===id)){select(id);place(item.id,b);}});}
 for(const item of shuffle(items)){const b=document.createElement('button');b.className='game-button house-item';b.dataset.item=item.id;b.draggable=true;b.setAttribute('aria-pressed','false');b.innerHTML=`<img src="${item.src}" alt=""><span>${item.name}</span>`;tray.append(b);ctx.on(b,'click',()=>select(item.id));ctx.on(b,'dragstart',e=>{select(item.id);e.dataTransfer.setData('text/plain',item.id);});}
 hud();ctx.status('Molly’s house needs a tidy. Choose an item to begin.');ctx.every(()=>{hud();if(ctx.elapsed>=60)ctx.finish({score:placed.size*100,won:false,message:`${placed.size} of 6 things tidied. Give the house another visit!`});},250);
}
function drawing(ctx){ctx.root.innerHTML='<p class="game-note" id="drawing-goals">Artist challenge: make 3 strokes, use 2 colours, and add a dog stamp.</p>';const{canvas,g,w,h,point}=ctx.canvas(900,500);canvas.style.background='#fff8ee';canvas.tabIndex=0;canvas.setAttribute('aria-label','Drawing canvas. Arrows move the brush; Space toggles drawing.');g.fillStyle='#fff8ee';g.fillRect(0,0,w,h);let x=450,y=250,down=false,keyboardInk=false,colour='#6b4f92',width=8,strokes=0,stamps=0,colours=new Set(),travel=0;const undo=[];
 const controls=document.createElement('div');controls.className='paint-toolbar';controls.innerHTML=['#6b4f92','#e47c70','#527f70','#e4b443','#343047'].map((c,i)=>`<button type="button" class="swatch" style="--paint:${c}" data-colour="${c}" aria-label="${['Purple','Coral','Green','Gold','Ink'][i]} brush" aria-pressed="${i===0}"></button>`).join('')+'<label>Brush <input aria-label="Brush size" type="range" min="3" max="30" value="8"></label><button class="game-button" data-stamp="molly">Molly stamp</button><button class="game-button" data-stamp="shaina">Shaina stamp</button><button class="game-button" data-action="undo">Undo</button><button class="game-button" data-action="clear">Clear</button><button class="game-button" data-action="save">Save here</button><button class="game-button" data-action="load">Load saved</button><button class="game-button" data-action="download">Download PNG</button><button class="primary-button" data-action="finish" disabled>Finish masterpiece</button>';ctx.root.append(controls);
 function update(){ctx.hud({Strokes:strokes,Colours:colours.size,Stamps:stamps});const ready=strokes>=3&&colours.size>=2&&stamps>=1;controls.querySelector('[data-action=finish]').disabled=!ready;$(ctx,'#drawing-goals').textContent=`${strokes>=3?'✓':'○'} 3 strokes (${Math.min(3,strokes)}/3) · ${colours.size>=2?'✓':'○'} 2 colours (${Math.min(2,colours.size)}/2) · ${stamps?'✓':'○'} Dog stamp`;}
 function snapshot(){undo.push({pixels:g.getImageData(0,0,w,h),strokes,stamps,colours:[...colours]});if(undo.length>15)undo.shift();}
 function line(nx,ny){g.strokeStyle=colour;g.lineWidth=width;g.lineCap='round';g.lineJoin='round';g.beginPath();g.moveTo(x,y);g.lineTo(nx,ny);g.stroke();travel+=Math.hypot(nx-x,ny-y);colours.add(colour);x=nx;y=ny;}
 function end(){if(down||keyboardInk){if(travel>4)strokes++;travel=0;down=false;keyboardInk=false;update();}}
 ctx.on(canvas,'pointerdown',e=>{e.preventDefault();end();snapshot();const p=point(e);x=p.x;y=p.y;down=true;canvas.setPointerCapture(e.pointerId);canvas.focus();});ctx.on(canvas,'pointermove',e=>{if(down){const p=point(e);line(p.x,p.y);}});ctx.on(canvas,'pointerup',end);ctx.on(canvas,'pointercancel',end);ctx.on(canvas,'lostpointercapture',end);
 ctx.on(canvas,'keydown',e=>{if(e.code==='Space'){e.preventDefault();if(keyboardInk)end();else{snapshot();keyboardInk=true;travel=0;ctx.status('Ink on. Use arrow keys to draw. Space lifts the brush.');}}const d={ArrowLeft:[-12,0],ArrowRight:[12,0],ArrowUp:[0,-12],ArrowDown:[0,12]}[e.code];if(d){e.preventDefault();const nx=Math.max(0,Math.min(w,x+d[0])),ny=Math.max(0,Math.min(h,y+d[1]));if(keyboardInk)line(nx,ny);else{x=nx;y=ny;ctx.status(`Brush at ${Math.round(x)}, ${Math.round(y)}. Space turns ink on.`);}}});ctx.on(canvas,'blur',end);
 function download(){const a=document.createElement('a');a.href=canvas.toDataURL();a.download='molly-and-shaina-masterpiece.png';a.click();}
 ctx.on(controls,'click',e=>{const b=e.target.closest('button');if(!b)return;end();if(b.dataset.colour){colour=b.dataset.colour;controls.querySelectorAll('[data-colour]').forEach(c=>c.setAttribute('aria-pressed',String(c===b)));return;}if(b.dataset.stamp){const img=ctx.image(assets[b.dataset.stamp]);if(!img.complete||!img.naturalWidth){ctx.status('The dog stamp is loading. Try again in a moment.');return;}snapshot();g.drawImage(img,Math.max(0,Math.min(w-100,x-50)),Math.max(0,Math.min(h-100,y-50)),100,100);stamps++;ctx.sound('good');}
 const action=b.dataset.action;if(action==='undo'&&undo.length){const old=undo.pop();g.putImageData(old.pixels,0,0);strokes=old.strokes;stamps=old.stamps;colours=new Set(old.colours);}if(action==='clear'){snapshot();g.fillStyle='#fff8ee';g.fillRect(0,0,w,h);strokes=stamps=0;colours.clear();}if(action==='download')download();if(action==='save'){try{localStorage.setItem(DRAWING_KEY,JSON.stringify({version:1,image:canvas.toDataURL(),strokes,stamps,colours:[...colours]}));ctx.status('Your masterpiece is saved in this browser.');}catch{ctx.status('Saving is unavailable. Download your PNG to keep a copy.');}}if(action==='load'){try{const saved=JSON.parse(localStorage.getItem(DRAWING_KEY)||'null');if(!saved||saved.version!==1||!/^data:image\/png;base64,/.test(saved.image))throw new Error();const img=new Image();img.onload=()=>{if(!ctx.alive)return;snapshot();g.clearRect(0,0,w,h);g.drawImage(img,0,0,w,h);strokes=Math.max(0,Math.min(1000,Number(saved.strokes)||0));stamps=Math.max(0,Math.min(1000,Number(saved.stamps)||0));colours=new Set(Array.isArray(saved.colours)?saved.colours.filter(c=>/^#[\da-f]{6}$/i.test(c)).slice(0,5):[]);update();ctx.status('Your saved drawing is back on the canvas.');};img.src=saved.image;}catch{ctx.status('No saved drawing yet. Make something and choose Save here.');}}if(action==='finish'&&strokes>=3&&colours.size>=2&&stamps){ctx.finish({score:Math.min(1000,strokes*40+colours.size*80+stamps*60),won:true,message:'Paw-casso would be proud. Download your masterpiece to keep it.',drawing:canvas.toDataURL()});return;}update();});ctx.on(controls.querySelector('input'),'input',e=>width=Number(e.target.value));ctx.image(assets.molly);ctx.image(assets.shaina);ctx.status('Create something in your own style. There’s no timer here.');update();
}
function versus(ctx){ctx.root.innerHTML=`<div class="game-board"><p class="game-note">You’re Molly. Shaina races automatically. Step while the moving marker is inside the green zone.</p><div class="race-track" aria-label="Molly’s lane"><img class="race-dog" src="${assets.molly}" alt="Molly"></div><div class="race-track" aria-label="Shaina’s lane"><img class="race-dog" src="${assets.shaina}" alt="Shaina"></div><div class="rhythm-bar" aria-label="Timing meter"><span class="rhythm-zone"></span><span class="rhythm-cursor"></span></div><div class="game-controls"><button class="primary-button" id="race-step">Step! · Space</button></div></div>`;let molly=0,shaina=0,marker=0,lastStep=-1,perfect=0,misses=0;const dogs=ctx.root.querySelectorAll('.race-dog'),bar=$(ctx,'.rhythm-cursor');function step(){if(ctx.elapsed-lastStep<.27)return;lastStep=ctx.elapsed;if(marker>=.4&&marker<=.6){const bull=Math.abs(marker-.5)<.035;molly+=bull?15:10;perfect+=bull?1:0;ctx.sound('good');ctx.status(bull?'Perfect paw! +15':'Good step! +10');}else{molly=Math.max(0,molly-3);misses++;ctx.sound('bad');ctx.status('A little early or late. Aim for the green zone.');}if(molly>=100)ctx.finish({score:Math.max(300,1400-Math.floor(ctx.elapsed)*15-misses*20+perfect*40),won:true,message:'Molly wins the household crown. A victory nap is scheduled.'});}ctx.on($(ctx,'#race-step'),'click',step);ctx.on(document,'keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();step();}});ctx.frame((dt,t)=>{marker=(Math.sin(t*(3.8+t*.015))+1)/2;bar.style.left=`${marker*99}%`;shaina+=dt*(2.3+Math.min(t,30)*.012);dogs[0].style.transform=`translateX(${molly/100*(dogs[0].parentElement.clientWidth-90)}px)`;dogs[1].style.transform=`translateX(${Math.min(100,shaina)/100*(dogs[1].parentElement.clientWidth-90)}px)`;ctx.hud({Molly:`${Math.min(100,molly)}%`,Shaina:`${Math.floor(shaina)}%`,Perfect:perfect});if(shaina>=100)ctx.finish({score:Math.floor(molly*6),won:false,message:'Shaina takes this round! Steady timing will give Molly the edge next time.'});});ctx.status('Follow the marker. Green means go.');}
function ultimate(ctx){let round=0,lives=3,score=0,token=0,deadline=0,accept=false,mode='',answer=0,sequence=[],input=[],lit=-1,buttons=[];ctx.root.innerHTML='<div class="game-board"><div class="meter"><div class="meter-fill" id="finale-time" style="width:100%"></div></div><h2 id="finale-prompt" style="margin:24px 0 12px"></h2><div id="finale-content"></div><div class="game-controls"><button class="primary-button" id="finale-next" hidden>Next round</button></div></div>';const content=$(ctx,'#finale-content'),prompt=$(ctx,'#finale-prompt'),next=$(ctx,'#finale-next');let limit=10;
 function hud(){ctx.hud({Round:`${round} / 12`,Hearts:'♥'.repeat(lives)+'♡'.repeat(3-lives),Score:score});}
 function complete(good,message){if(!accept)return;accept=false;if(good){score+=100+round*20+Math.max(0,Math.floor((deadline-ctx.elapsed)*10));ctx.sound('good');}else{lives--;ctx.sound('bad');}hud();ctx.status(message);buttons.forEach(b=>b.disabled=true);if(lives<=0){ctx.later(()=>ctx.finish({score,won:false,message:`Your best effort reached round ${round} of 12. Come back for another championship run.`}),900);return;}if(round>=12){ctx.later(()=>ctx.finish({score,won:true,message:'Twelve rounds. One ultimate good dog. You conquered the arcade finale!'}),900);return;}next.hidden=false;next.focus();}
 function choose(i){if(!accept)return;if(mode==='sequence'){input.push(i);buttons[i].classList.add('lit');const b=buttons[i];ctx.later(()=>b.classList.remove('lit'),180);if(sequence[input.length-1]!==i){complete(false,'The trail went another way. One heart lost.');return;}ctx.sound('tap');if(input.length===sequence.length)complete(true,'Perfect memory. On to the next challenge.');}else complete(i===answer,i===answer?'Excellent paws. Round cleared!':`Not this time. ${mode==='photo'?`That was ${photos[answerPhoto].dog}.`:mode==='trivia'?explanation:'Follow the bone, not the distractions.'}`);}
 let answerPhoto=0,explanation='';
 function begin(){round++;token++;const current=token;limit=Math.max(4.5,11-round*.45);deadline=0;accept=false;next.hidden=true;content.replaceChildren();buttons=[];mode=['photo','spot','sequence','trivia'][(round-1)%4];hud();ctx.status(`Round ${round}: ${mode==='sequence'?'watch first, then repeat.':'one choice before time runs out.'}`);if(mode==='photo'){const p=randomInt(0,photos.length-1);answerPhoto=p;answer=photos[p].dog==='Molly'?0:1;prompt.textContent='Who is this?';const img=document.createElement('img');img.className='finale-photo';img.src=photos[p].src;img.alt='Identify the dog in this photo';content.append(img);addButtons(['Molly','Shaina']);}
 if(mode==='spot'){answer=randomInt(0,5);prompt.textContent='Find the treat!';addButtons(Array.from({length:6},(_,i)=>i===answer?'🦴':['🍃','🧦','🪨','🌼'][randomInt(0,3)]));}
 if(mode==='trivia'){const q=shuffle(trivia)[0],opts=shuffle(q.options.map((text,i)=>({text,correct:i===q.answer})));answer=opts.findIndex(o=>o.correct);explanation=q.explanation;prompt.textContent=q.question;addButtons(opts.map(o=>o.text));const source=document.createElement('a');source.href=q.source;source.textContent='Read the site fact ↗';source.className='game-note';source.target='_blank';source.rel='noopener';content.append(source);}
 if(mode==='sequence'){prompt.textContent='Watch the paw trail…';sequence=Array.from({length:2+Math.floor(round/4)},()=>randomInt(0,3));input=[];addButtons(['🐾','🐾','🐾','🐾']);buttons.forEach(b=>b.disabled=true);sequence.forEach((n,i)=>{ctx.later(()=>{if(token!==current)return;buttons[n].classList.add('lit');ctx.sound('tap');},600+i*650);ctx.later(()=>{if(token===current)buttons[n].classList.remove('lit');},1000+i*650);});ctx.later(()=>{if(token!==current)return;prompt.textContent=`Repeat the ${sequence.length}-step trail`;buttons.forEach(b=>b.disabled=false);accept=true;deadline=ctx.elapsed+limit;},700+sequence.length*650);}else{accept=true;deadline=ctx.elapsed+limit;}}
 function addButtons(labels){const box=document.createElement('div');box.className='finale-targets';labels.forEach((label,i)=>{const b=document.createElement('button');b.className='game-button';b.innerHTML=`<small style="display:block;font-size:.7rem;color:inherit">${i+1}</small><span></span>`;b.querySelector('span').textContent=label;b.setAttribute('aria-label',`${i+1}: ${label}`);box.append(b);buttons.push(b);ctx.on(b,'click',()=>choose(i));});content.append(box);}
 ctx.on(next,'click',begin);ctx.on(document,'keydown',e=>{const i=Number(e.key)-1;if(!e.repeat&&i>=0&&i<buttons.length&&e.key!==' '){e.preventDefault();choose(i);}});ctx.frame(()=>{if(accept){const left=deadline-ctx.elapsed;$(ctx,'#finale-time').style.width=`${Math.max(0,left/limit*100)}%`;if(left<=0)complete(false,'Time slipped away. Take a breath for the next round.');}});begin();
}
export const games={'pawprint-maze':maze,'sniff-hunt':sniff,'mollys-house':house,'doggy-drawing':drawing,'molly-vs-shaina':versus,'ultimate-dog-challenge':ultimate};
