export const randomInt = (min,max) => Math.floor(Math.random()*(max-min+1))+min;
export function shuffle(items) { const a=[...items]; for(let i=a.length-1;i>0;i--){const j=randomInt(0,i);[a[i],a[j]]=[a[j],a[i]];}return a; }
export const photos = [
  ...['looking toward the camera','in a close-up portrait','curled up on folded towels','resting on a patterned rug','sitting beside a phone'].map((alt,i)=>({id:`molly-${i}`,dog:'Molly',src:`/images/molly/molly${i}.webp`,alt:`Molly ${alt}`})),
  ...['with a tennis ball','relaxing in sunlight','beneath an orange towel','carrying a plush toy'].map((alt,i)=>({id:`shaina-${i+1}`,dog:'Shaina',src:`/images/shaina/shaina${i+1}.webp`,alt:`Shaina ${alt}`}))
];
const q=(question,options,explanation,source)=>({question,options,answer:0,explanation,source});
// All answers sourced from the existing site. Age questions omitted so the quiz does not age out.
export const trivia=[
 q('What breed is Molly?',['Cavamalt','Border Collie','Toy Poodle','Beagle'],'Molly’s About page calls her a Cavamalt: part Cavoodle, part Maltese.','/about-molly/'),
 q('What is Molly’s favourite activity?',['Sleeping','Swimming','Fetching','Digging'],'Molly’s About page names sleep as her favourite activity.','/about-molly/'),
 q('What does Molly steal from the laundry basket?',['Towels','Shoes','Hats','Tennis balls'],'Molly steals towels from the laundry basket.','/about-molly/'),
 q('Which is one of Molly’s nicknames?',['Meowy','Captain Zoom','Pickles','Snowball'],'Molly’s nicknames include Molly Dog and Meowy.','/about-molly/'),
 q('What does Molly do around dogs that seem too big or unfriendly?',['Leaves','Starts a fight','Steals their toys','Performs tricks'],'Molly prefers to leave when another dog seems too big or unfriendly.','/about-molly/'),
 q('What breed mix is Shaina?',['Shih Tzu and Maltese','Cavoodle and Maltese','Labrador and Poodle','Beagle and Pug'],'Shaina is a Shih Tzu and Maltese mix.','/about-shaina/'),
 q('Which spoken words can make Shaina respond?',['Woof or bark','Hello or goodbye','Left or right','Please or thanks'],'Shaina responds when someone says “woof” or “bark”.','/about-shaina/'),
 q('Which fruit’s peels interest Shaina?',['Orange','Banana','Apple','Mango'],'Shaina’s About page describes her relationship with orange peels.','/about-shaina/'),
 q('Compared with Molly, Shaina…',['Sleeps less and barks more','Sleeps more and barks less','Sleeps all day','Never barks'],'Her About page says Shaina sleeps less and barks more than Molly.','/about-shaina/'),
 q('What nickname describes Molly’s spinning tail?',['Helicopter Tail','Rocket Tail','Feather Tail','Compass Tail'],'Molly’s tail spins when she gets excited: Helicopter Tail.','/molly-traits/'),
 q('What does Molly reshape blankets into?',['Nests','Hats','Flags','Kites'],'Molly’s Blanket Architecture turns each blanket into a nest.','/molly-habits/'),
 q('What does Molly monitor during Window Patrol?',['Leaves, birds and clouds','The television','Fish','Traffic lights'],'Window Patrol keeps an eye on leaves, birds and clouds.','/molly-habits/'),
 q('How does Molly regard toys?',['Decorative objects','Essential treasures','Scary enemies','Her favourite food'],'Her FAQ says toys are decorative objects, inspected once and then ignored.','/molly-faq/'),
 q('What does Shaina carry in her playful gallery photo?',['A plush toy','A sock','An orange','A newspaper'],'The gallery shows Shaina carrying a plush toy across the rug.','/shaina-gallery/'),
 q('What does Shaina learn quickly?',['Routines','Bird songs','Numbers','Swimming strokes'],'Shaina learns routines quickly and notices when the pattern changes.','/shaina-mind/')
];
const emoji='/images/emoji/'; const sticker='/images/merch/stickers/';
export const catalog=[
 ['memory-match','Memory Match','Find the familiar faces hiding in twelve photo cards.','Brain games','Easy','molly-emoji.webp','🃏','Reveal two cards at a time. Match all six pairs before the timer runs out.',['Tap cards, or Tab then Enter.','Fewer turns and faster matches earn more points.']],
 ['treat-catch','Treat Catch','A snack shower. Three lives. One very happy Molly.','Quick paws','Easy','molly-emoji.webp','🦴','Catch falling treats and dodge the hazards for 45 seconds.',['Move with ← / → or A / D.','Drag on the playfield or hold the on-screen arrows.']],
 ['wheres-molly',"Where’s Molly?",'Follow the shuffle. Keep your eyes on the towel.','Brain games','Medium','molly-emoji.webp','👀','Watch Molly hide under a towel, follow the shuffle and choose her hiding place.',['Tap a hiding place or use its number key.','Five rounds get faster. Keep at least one life.']],
 ['trivia','Molly & Shaina Trivia','How well do you know your favourite suspicious dogs?','Brain games','Easy','faq-emoji.webp','💭','Answer ten questions drawn from the real Molly & Shaina website.',['Tap an answer or use number keys.','Get at least seven right. Every answer has a source.']],
 ['pawprint-maze','Pawprint Maze','A winding trail from dog headquarters to dinner.','Brain games','Medium','molly-emoji.webp','🐾','Guide Molly through the maze, collect three treats and reach the bowl in 90 seconds.',['Use arrow keys / WASD or the on-screen arrows.','Walls block movement. Every maze has a route.']],
 ['molly-dash','Molly Dash','Naps can wait. The hallway obstacle course is open.','Quick paws','Medium','molly-emoji.webp','⚡','Jump the obstacles and collect treats on Molly’s increasingly speedy run.',['Press Space / ↑ or tap Jump.','Survive to the finish. A collision costs a life.']],
 ['fetch','Fetch!','Find the angle. Land the ball. Make Shaina’s day.','Quick paws','Medium','shaina-emoji.webp','🎾','Aim five throws into the moving landing zone for Shaina.',['Adjust angle and power with the sliders.','Use keyboard sliders, then Enter on Throw.']],
 ['who-is-it','Who Is It?','Two familiar faces. Eight photo identifications.','Brain games','Easy','gallery-emoji.webp','📷','Identify the dog in eight real gallery photographs.',['Tap Molly or Shaina, or use the indicated key.','Recognise at least six photos to win.']],
 ['photo-puzzle','Photo Puzzle','Piece together a favourite moment, one slide at a time.','Brain games','Medium','gallery-emoji.webp','🧩','Slide the photo tiles into order, leaving the empty square at the bottom right.',['Tap a tile beside the gap, or use arrow keys.','Every shuffle is solvable. Numbers and preview help.']],
 ['treat-stacker','Treat Stacker','Build a snack tower. Precision is everything.','Quick paws','Hard','habits-emoji.webp','🥞','Drop each moving treat onto the tower. Overhanging pieces fall away.',['Press Space or tap Drop.','Stack twelve levels; miss the tower and the run ends.']],
 ['sniff-hunt','Sniff Hunt','Follow your nose to three well-hidden treats.','Brain games','Medium','mind-emoji.webp','🔎','Find three hidden treats in the garden within twelve digs.',['Tap a square, or move the focus with arrows and press Enter.','Each empty dig tells you the distance to the nearest treat.']],
 ['mollys-house',"Molly’s House",'Put everything in its place. Molly has standards.','Play & create','Easy','home-emoji.webp','🏡','Tidy Molly’s house by matching six items to their named places.',['Select an item, then select its destination.','Drag and drop also works. Finish within 60 seconds.']],
 ['reaction-paws','Reaction Paws','Wait for green. Prove you have Shaina-level reflexes.','Quick paws','Medium','shaina-emoji.webp','⏱','React to the green cue over five rounds. Don’t jump the gun.',['Press Space or tap the reaction pad.','Three false starts or misses end the session.']],
 ['doggy-drawing','Doggy Drawing','A little colour. A lot of character. Your dog masterpiece.','Play & create','Relaxed','molly-emoji.webp','🎨','Create a dog-inspired drawing. Complete three creative steps to earn your artist badge.',['Draw with a mouse or finger; choose colours and stamps.','Keyboard: arrows move the brush, Space toggles ink. Save or download your work.']],
 ['molly-vs-shaina','Molly vs Shaina','A perfectly timed dash for the household crown.','Quick paws','Hard','shaina-emoji.webp','🏁','Race as Molly against Shaina. Time your steps when the marker is in the green zone.',['Press Space or tap Step in the green zone.','Good timing moves you forward; misses slow you down. First to 100 wins.']],
 ['ultimate-dog-challenge','Ultimate Dog Challenge','The finale. Memory, reflexes, recognition and one epic run.','Play & create','Expert','shaina-emoji.webp','🏆','Take on twelve mixed rounds that get faster and trickier. Three hearts stand between you and dog greatness.',['Rounds mix memory sequences, treat spotting, photo recognition and trivia.','Tap or use number keys. Complete twelve rounds and record your best run.']]
].map(([id,title,description,category,difficulty,file,symbol,instructions,controls],i)=>({id,title,description,category,difficulty,image:emoji+file,symbol,instructions,controls,number:i+1,tint:['#df9177','#9f8edd','#79bdac','#cfac66'][i%4]}));
export const assets={molly:emoji+'molly-emoji.webp',shaina:emoji+'shaina-emoji.webp',bone:sticker+'dog-bone.webp',ball:sticker+'tennis-ball.webp'};
